apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Uma api com elysia e bun.
  annotations:
    github.com/project-slug: gabrielmelogm/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental